#cloud-config
autoinstall:
  version: 1
  # Configurações de identidade do usuário e sistema
  identity:
    realname: "Nome do Usuário"
    hostname: ubuntu-pc
    username: usuario
    # Gere uma senha criptografada com: mkpasswd --method=sha-512
    password: "$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3"
  locale: pt_BR.utf8
  keyboard:
    layout: br
  timezone: "America/Sao_Paulo"

  # Seção de instalação de pacotes via APT (.deb)
  # Agrupamos os pacotes por funcionalidade e incluímos comentários para facilitar a manutenção
  packages:
    # Utilitários básicos e ferramentas de rede
    - curl
    - wget
    - git
    - 7zip

    # Ferramentas de multimídia e produtividade
    - gimp
    - libreoffice
    - firefox
    - vlc

    # Utilitários para desenvolvimento e configuração do sistema
    - gnome-tweaks
    - mesa-utils
    - pipewire

    # Softwares para manipulação de imagens ISO
    - xorriso      # Para criação e manipulação de imagens ISO
    - genisoimage  # Contém o comando mkisofs

  # Seção de instalação de aplicativos via Snap
  snaps:
    - name: btop
      channel: latest/stable
    - name: chromium
      channel: latest/stable
    - name: firefox
      channel: latest/stable
    - name: vlc
      channel: latest/stable
    - name: snap-store
      channel: latest/stable
    - name: terminal-parrot
      channel: latest/stable

  # Seção de instalação de aplicativos via Flatpak
  flatpaks:
    - app.fotema.Fotema
    - app.zen_browser.zen
    - cc.arduino.IDE2
    - com.github.huluti.Curtail
    - com.github.tchx84.Flatseal
    - com.google.Chrome
    - com.mattjakeman.ExtensionManager
    - com.valvesoftware.Steam
    - de.haeckerfelix.Fragments
    - de.haeckerfelix.Shortwave
    - eu.nokun.MirrorHall
    - info.febvre.Komikku
    - io.github.peazip.PeaZip
    - io.gitlab.adhami3310.Converter
    - io.gitlab.news_flash.NewsFlash
    - org.dupot.easyflatpak
    - org.kde.isoimagewriter
    - org.thonny.Thonny

  # Instalação automática de codecs e drivers proprietários ou adicionais
  codecs:
    install: true

  drivers:
    install: true

  # Atualizações automáticas: 'all' garante que todas as atualizações sejam aplicadas
  updates: all

  # Ação pós-instalação: reinicia o sistema ao final da instalação
  shutdown: reboot

  # Seção para comandos executados após a instalação (pós-instalação)
  # Ideal para configurações customizadas que não podem ser definidas diretamente via YAML
  late-commands:
    - curtin in-target --target=/target -- sh -c 'echo "Pós-instalação executada com sucesso!"'
